---
title: "A Energia Solar é Verdadeiramente Limpa? Uma análise sobre os problemas dos resíduos fotovoltaicos"
description: |
  A short description of the post.
author:
  - name: Andreza de Aguiar Hugo
    url: ../../pesquisadores/andreza_aguiar.html
date: 2025-03-28
output:
  distill::distill_article:
    self_contained: false
---

```{css, echo=FALSE}
.paragrafo1 {
  font-family: 'Archivo';
  font-weight: bold; /* Deixa o texto em negrito */
  text-align: justify; /* Justifica o texto */
  color: #384955;
}

.referencias {
  font-family: 'Archivo Black';
  font-weight: bold; /* Deixa o texto em negrito */
  text-align: justify; /* Justifica o texto */
  color: #384955;
}
```

<p class="paragrafo1">A energia solar veio como uma ótima solução de geração de energia renovável, uma vez que não gera emissões adicionais. Assim, diversos países vêm investindo e incentivando a instalação de painéis fotovoltaicos e o Brasil é um deles. Para se ter ideia, o plano de ação climática do estado de Minas Gerais prevê como uma das metas de energia, a expansão da capacidade instalada de usinas fotovoltaicas para geração de 5,9 GW até 2030 e 18,9 GW até 2050.</p>


<p class="paragrafo1">No entanto, como nem tudo são flores, a energia solar também apresenta desafios ambientais com relação à desativação dos painéis fotovoltaicos, responsáveis pela geração de energia. Estes painéis, possuem, em média, uma vida útil de 25 anos e muitos deles já foram ou estão prestes a serem descartados. A problemática envolta deste descarte, diz respeito aos materiais residuais presentes nos painéis, que podem ser prejudiciais ao meio ambiente, caso não sejam destinados corretamente, devido suas toxidades, além do alto volume de resíduos descartados em aterros sanitários, que poderiam ter sido reaproveitados de outras formas.</p>


<p class="paragrafo1">Diante disso, a principal solução encontrada, até o momento, para mitigar os impactos ambientais gerados pelo descarte dos painéis fotovoltaicos é a reciclagem. Assim, diversas pesquisas vêm sendo realizadas a respeito da reciclagem dos materiais presentes nestes resíduos, mas ainda existem muitas barreiras que impedem o aumento do volume da coleta e reciclagem. Dentre elas estão a baixa lucratividade da reciclagem e a falta de uma regulamentação que direcione a correta gestão e destinação destes resíduos.</p>


<p class="paragrafo1">Nesse sentindo, buscando regulamentar essa questão, está em andamento no Brasil, um Projeto de Lei n° 3784, de 2023 em que será exigida a obrigatoriedade dos fabricantes, importadores, distribuidores e comerciantes de painéis solares fotovoltaicos a estruturar e implementar sistemas de logística reversa (Brasil, 2023). Porém, os painéis solares presentes no Brasil são de origem estrangeira e por mais que o novo Projeto de Lei preveja a obrigatoriedade do importador de implementar logística reversa de resíduos fotovoltaicos, sabemos das dificuldades/burocracias desse translado. Ainda mais para um resíduo que é gerado à longo prazo, o que pode causar imprevistos, como a saída do importador desse mercado de energia solar, quando os painéis chegarem ao fim de vida útil.</p>


<p class="paragrafo1">Na Europa, os resíduos de painéis solares são tratados como resíduos de equipamentos elétricos e eletrônicos. Já o Projeto de Lei em andamento no Brasil afirma que estes resíduos não se enquadram no conceito de produtos eletroeletrônicos estabelecido pelo Decreto nº 10.240, de 12 de fevereiro de 2020, havendo assim, uma contradição no instrumento normativo, o que dificulta ainda mais o gerenciamento correto dos materiais oriundos do descarte das placas fotovoltaicas.</p>


<p class="paragrafo1">Sendo assim, o artigo científico dos autores brasileiros da Universidade Federal de Santa Maria é cirúrgico ao dizer que a rápida expansão da energia solar no país se desenvolve em um ambiente sem regulamentações específicas, representando um desafio substancial à sustentabilidade do setor. Os autores ainda afirmam, que a ausência de diretrizes claras pode resultar no descarte inadequado de equipamentos fotovoltaicos, ameaçando a sustentabilidade e a competitividade de longo prazo dessa fonte de energia. Além disso, apesar do potencial significativo para reaproveitamento desses materiais, há uma lacuna de conhecimento sobre como aumentar seu valor pós-uso e integrá-los a um modelo de negócio viável (Spellmeier et al., 2025).
Podemos concluir, portanto, que as soluções para um gerenciamento correto dos resíduos fotovoltaicos estão andando a passos lentos, assim como eles demoram a ser gerados. No entanto, a natureza necessita de respostas rápidas, já que são estimadas a geração de 8 milhões de toneladas de resíduos de módulos fotovoltaicos até 2030 (IRENA, 2016).</p>


<p class="paragrafo1">Por fim, ainda podemos ressaltar que faltam pesquisas que se concentrem em analisar os resíduos fotovoltaicos na visão da economia circular. Isto é, quais os meios mais eficientes para realizar o gerenciamento destes resíduos, bem como buscar soluções além da reciclagem e principalmente, como produzir painéis solares com materiais menos prejudiciais ao meio ambiente trazendo como objetivo os princípios do eco design. Todas essas questões, no entanto, não invalidam os grandes benefícios da geração fotovoltaica para o mundo, elas só precisam ser seriamente consideradas para que a energia solar seja verdadeiramente limpa.</p>


<p class="referencias">Referências</p>

<p class="paragrafo1">Brasil. (2023), PROJETO DE LEI N° 3784, DE 2023.</p>

<p class="paragrafo1">IRENA - International Renewable Energy Agency. (2016), “End-Of-Life Management: Solar Photovoltaic Panels”, available at: https://www.irena.org/publications/2016/Jun/End-of-life-management-Solar-Photovoltaic-Panels (accessed 24 March 2025).</p>

<p class="paragrafo1">Spellmeier, J.P., Rosa, C.B., Rigo, P.D., Mello, M.F. and Hoss, M. (2025), “Design of a business model for competitive end-of-life performance of photovoltaic systems in Brazil”, Renewable Energy, Vol. 245, p. 122755, doi: 10.1016/j.renene.2025.122755.</p>
