---
title: "Maiores fornecedores de placas solares por mesorregião em Minas Gerais"
description: |
  Dados referentes ao ano de 2023.
author: 
  - name: "Bruno Luppe"
    affiliation: "UNIFEI"
    affiliation_url: https://unifei.edu.br
    url: ../../pesquisadores/bruno_luppe.html
  - name: "Paulo Augusto"
    affiliation: "UNIFEI"
    affiliation_url: https://unifei.edu.br
    url: ../../pesquisadores/paulo_augusto.html
  - name: "Victor Valério"
    url: ../../pesquisadores/victor_valerio.html
    affiliation: "UNIFEI"
    affiliation_url: https://unifei.edu.br
date: 2024-05-22

output:
  distill::distill_article:
    self_contained: false
---

[Inserir texto]

```{r setup, include=FALSE}
library(magrittr)
library(ggplot2)

fornecedores_geral_quadrado <- readr::read_csv2(file = 'fornecedores_geral_quadrado.csv')

meso_mapa <- geobr::read_meso_region(code_meso = 'MG') %>% 
  dplyr::mutate(name_meso = stringr::str_to_upper(name_meso)) %>%  
  dplyr::full_join(fornecedores_geral_quadrado,
                   by = c('name_meso' = 'name_meso')) %>% 
  ggplot()+
  geom_sf(mapping = aes(fill = Freq))+
  geom_sf_text(mapping = aes(label = nom_fabricante_modulo), color = 'white')

```

```{r echo=FALSE}
meso_mapa
```